<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
      <link rel="stylesheet" type="text/css" media="screen"
             href="<?php echo $this->baseUrl();?>/css/site.css" />
</head>
<body>
  <a href="<?php echo $this->baseUrl();?>">Home</a>
  <a href="<?php echo $this->url(array('controller'=>'index',
          'action'=>'add'));?>">Add Item</a>
          <a href="<?php echo $this->url(array('controller'=>'index',
          'action'=>'showall'));?>">Show All (short view)</a>
<h1><img src="<?php echo $this->baseUrl();?>/images/psiheader.gif"/></h1>
<div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>